wandb_version: 1

resume_run_id:
  desc: null
  value: null
urdf_ds_name:
  desc: null
  value: bracket_assembly
object_ds_name:
  desc: null
  value: bracket_assembly_nut
n_symmetries_batch:
  desc: null
  value: 64
train_ds_names:
  desc: null
  value:
  - - bracket_assembly_nut
    - 1
val_ds_names:
  desc: null
  value:
  - - bracket_assembly_nut
    - 1
val_epoch_interval:
  desc: null
  value: 50
test_ds_names:
  desc: null
  value: []
test_epoch_interval:
  desc: null
  value: 30
n_test_frames:
  desc: null
  value: 100
input_resize:
  desc: null
  value:
  - 640
  - 480
rgb_augmentation:
  desc: null
  value: false
background_augmentation:
  desc: null
  value: false
gray_augmentation:
  desc: null
  value: false
backbone_str:
  desc: null
  value: efficientnet-b3
run_id_pretrain:
  desc: null
  value: null
n_pose_dims:
  desc: null
  value: 9
n_rendering_workers:
  desc: null
  value: 8
refiner_run_id_for_test:
  desc: null
  value: null
coarse_run_id_for_test:
  desc: null
  value: null
lr:
  desc: null
  value: 3.0e-05
weight_decay:
  desc: null
  value: 0.0
n_epochs_warmup:
  desc: null
  value: 100
lr_epoch_decay:
  desc: null
  value: 500
clip_grad_norm:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 8
epoch_size:
  desc: null
  value: 115200
n_epochs:
  desc: null
  value: 100
n_dataloader_workers:
  desc: null
  value: 8
loss_disentangled:
  desc: null
  value: true
n_points_loss:
  desc: null
  value: 2600
TCO_input_generator:
  desc: null
  value: fixed
n_iterations:
  desc: null
  value: 1
min_area:
  desc: null
  value: null
config:
  desc: null
  value: bracket_assembly_nut_noaug_coarse
init_method:
  desc: null
  value: from_boxes
run_id:
  desc: null
  value: bracket_assembly_nut_noaug_coarse--917955
train_refiner:
  desc: null
  value: false
train_coarse:
  desc: null
  value: true
save_dir:
  desc: null
  value: /home/ubuntu/synthetic_pose_estimation/cosypose/local_data/experiments/bracket_assembly_nut_noaug_coarse--917955
n_gpus:
  desc: null
  value: 1
global_batch_size:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.7.6
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683268884.774068
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 54
      - 55
      3:
      - 16
      - 23
      4: 3.7.6
      5: 0.15.1
      8:
      - 5
